[project]
name = "deepseek-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.7.0",
    "numpy>=2.2.6",
    "sympy>=1.14.0",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]
